### ISSUE TITLE
Use versioned api path

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/dispatch#6]
**Is your feature request related to a problem? Please describe.**
Currently this service exposes its base controller under `/api/server`. This deviates from the pattern used across other services.

**Describe the solution you'd like**
Provide a versioned base endpoint and include the service name is the base path (e.g. `/api/dispatch/v1/`). The existing path should also be supported during a transition period.

**Comment by caspiano** [comment]
@tassja I'd have a grep of the codebase to see anywhere the dispatch service is used. This is a service without a client, so I'd be extra careful
